<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' Добавить' => ' Add',
    ' Назад' => ' Back',
    ' Сохранить' => ' Save',
    ' Удалить' => ' Delete',
    'Будьте осторожны! Вы можете утратить доступ к опции!' => 'Be careful! You may lose access to the option!',
    'Вкладка' => 'Tab',
    'Вкладка сохранена' => 'The tab is saved',
    'Вкладка удалена' => 'The tab is deleted',
    'Выбрать файл' => 'Choose file',
    'Группа' => 'Group',
    'Добавление элемента' => 'Add item',
    'Если запрещено изменение, то редактирование так же невозможно!' => 'If you can\'t change it, you can\'t edit it either!',
    'Защищенное' => 'Protected',
    'Здесь вы можете изменить права доступа к опции настройки' => 'Here you can change access rights to the settings option',
    'Значение' => 'Values',
    'Ключ' => 'Key',
    'Название' => 'Title',
    'Настройка добавлена' => 'Setting is added',
    'Настройка сохранена' => 'Setting is saved',
    'Настройка удалена' => 'Setting is deleted',
    'Настройки' => 'Settings',
    'Недостаточно прав' => 'Not enough rights',
    'Недостаточно прав!' => 'Not enough rights!',
    'Ошибка добавления: ' => 'Adding error: ',
    'Ошибка сохранения вкладки' => 'Error saving the tab',
    'Ошибка сохранения: ' => 'Saving error: ',
    'Ошибка удаления' => 'Deletion error',
    'Ошибка удаления вкладки' => 'Error deleting a tab',
    'Позиция' => 'Position',
    'Право изменения' => 'The right to change',
    'Право редактирования' => 'The right to edit',
    'Редактирование элемента: ' => 'Editing an element: ',
    'Тип' => 'Type',
    'Только чтение' => 'Read only',
];
