<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => 'Администратор',
    'Are you sure you want to delete this user?' => 'Вы уверены, что хотите удалить этого пользователя?',
    'Code can contain only a-z letters and _' => 'Код может содержать только буквы a-z и _',
    'Config' => 'Конфигурация',
    'Description' => 'Описание',
    'Economy' => 'Экономия',
    'Email' => 'Email',
    'ID' => 'ID',
    'Menu' => 'Меню',
    'Name' => 'Имя',
    'Pages' => 'Страницы',
    'Preview' => 'Предварительный просмотр',
    'Published' => 'Опубликованный',
    'Role add failed' => 'Ошибка добавления роли',
    'Role added successfully' => 'Роль добавленна успешно',
    'Role assigned to the user' => 'Роль назначена пользователю',
    'Role deleted successfully' => 'Роль удалена успешно',
    'Role deletion error' => 'Ошибка удаления роли',
    'Role get failed' => 'Ошибка получения роли',
    'Role is empty' => 'Роль пуста',
    'Role update failed' => 'Ошибка обновления роли',
    'Role updated successfully' => 'Роль успешно обновлена',
    'Sport' => 'Спорт',
    'Title' => 'Заголовок',
    'Update menu' => 'Обновление меню',
    'Url' => 'URL-адрес',
    'Users' => 'Пользователь',
    'Вы действительно хотите удалить данного пользователя?' => 'Are you sure you want to delete this user?',
    'Выбрать файл' => 'Choose file',
    'Группа' => 'Group',
    'Действия' => 'Action',
    'Добавить' => 'Add',
    'Добавить роль' => 'Add role',
    'Значение' => 'Value',
    'Изменить' => 'Modify',
    'Изменить роль: mode' => 'Edit role: mode',
    'Изменён' => 'Modified',
    'Имя' => 'Name',
    'Имя пользователя' => 'User name',
    'Класс иконки' => 'Icon class',
    'Ключ' => 'Key',
    'Код' => 'Code',
    'Назад' => 'Backward',
    'Название' => 'Title',
    'Новый пароль (если нужно изменить его)' => 'New password (if you need to change it)',
    'Обновить' => 'Update',
    'Описание' => 'Description',
    'Пароль' => 'Password',
    'Позиция' => 'Position',
    'Пользователи' => 'Users',
    'Пользователи и роли' => 'Users and roles',
    'Редактирование' => 'Editing',
    'Редактирование меню' => 'Editing the menu',
    'Роли' => 'Roles',
    'Роль' => 'Role',
    'Создан' => 'Created',
    'Создание меню' => 'Creating a menu',
    'Создать' => 'Create',
    'Создать меню' => 'Create Menu',
    'Создать пользователя' => 'Create User',
    'Сохранить' => 'Save',
    'Статус' => 'Status',
    'Тип' => 'Type',
    'Только чтение' => 'Only reading',
    'Удалить' => 'Delete',
];
